#include <cstdio>
#include <cstring>

#include "Pixee.h"

// Generated by qmake; guarded so a non-qmake build still compiles.
#if __has_include("BuildInfo.h")
#include "BuildInfo.h"
#endif

// Supplied by Pixee.pro from the VERSION file; fallback for non-qmake builds.
#ifndef APP_VERSION
#define APP_VERSION "0.0.0-dev"
#endif
// Build timestamp, generated into BuildInfo.h by qmake.
#ifndef BUILD_DATE
#define BUILD_DATE "unknown"
#endif

int main(int argc, char *argv[])
{
    // Answer --version / -v before spinning up the GUI. On Windows this app is
    // built for the GUI subsystem, so the text is only visible when stdout is
    // redirected (e.g. `Pixee.exe --version > v.txt`); on Linux it prints to
    // the terminal as usual.
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--version") == 0 || std::strcmp(argv[i], "-v") == 0) {
            std::printf("Pixee %s (built %s)\n", APP_VERSION, BUILD_DATE);
            return 0;
        }
    }

    Pixee pixee(argc, argv);
    return pixee.run();
}
